name: ecommerce
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.1.12
  get: ^4.6.6
  shared_preferences: ^2.2.2
  flutter_otp_text_field: ^1.1.1
  dartz: ^0.10.1
  http: ^1.2.0
  lottie: ^3.1.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_messaging: ^14.7.19
  flutter_svg: ^2.0.10+1
  animated_splash_screen: ^1.3.0
  persistent_bottom_nav_bar: ^5.0.2
  dropdown_search: ^5.0.6
  flutter_typeahead: ^5.2.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.0
  image_picker: ^1.0.8
  path: ^1.8.3
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  timezone: ^0.9.4
  flutter_timezone: ^1.0.8
  flutter_background_service: ^5.0.7
  flutter_image_compress: ^2.3.0
  image: ^4.2.0
  cached_network_image: ^3.3.1
  webview_flutter: ^4.5.0
  flutter_switch: ^0.3.2
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo 1.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - lottie/

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Bold.ttf
        - asset: fonts/Cairo-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf

