// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiXgmarayLRWyonr-9I6TKjfX5RBrUwUM',
    appId: '1:832425898824:web:410696efcc7620eb1db97d',
    messagingSenderId: '832425898824',
    projectId: 'ecommerce-68b81',
    authDomain: 'ecommerce-68b81.firebaseapp.com',
    storageBucket: 'ecommerce-68b81.appspot.com',
    measurementId: 'G-RWP3KD8WMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeTYj9c-Vj0Rd277-T00cZPQEKQZcK618',
    appId: '1:832425898824:android:ddf3d7d1a5ff108c1db97d',
    messagingSenderId: '832425898824',
    projectId: 'ecommerce-68b81',
    storageBucket: 'ecommerce-68b81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1CAKMSccIhJf8HwBds4T1jeF9CkIXaWg',
    appId: '1:832425898824:ios:01f2a623bc7244d51db97d',
    messagingSenderId: '832425898824',
    projectId: 'ecommerce-68b81',
    storageBucket: 'ecommerce-68b81.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1CAKMSccIhJf8HwBds4T1jeF9CkIXaWg',
    appId: '1:832425898824:ios:01f2a623bc7244d51db97d',
    messagingSenderId: '832425898824',
    projectId: 'ecommerce-68b81',
    storageBucket: 'ecommerce-68b81.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiXgmarayLRWyonr-9I6TKjfX5RBrUwUM',
    appId: '1:832425898824:web:de4b0a7973fcb1e01db97d',
    messagingSenderId: '832425898824',
    projectId: 'ecommerce-68b81',
    authDomain: 'ecommerce-68b81.firebaseapp.com',
    storageBucket: 'ecommerce-68b81.appspot.com',
    measurementId: 'G-XSCDP8CR07',
  );

}